# Generated by Django 4.1.5 on 2023-01-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksData',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=200)),
                ('year', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('publisher', models.CharField(blank=True, max_length=200, null=True)),
                ('image_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'books_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BooksRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=0, max_digits=4)),
            ],
            options={
                'db_table': 'books_rating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BooksUser',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=8, primary_key=True, serialize=False)),
                ('age', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('username', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'books_user',
                'managed': False,
            },
        ),
    ]
