# Generated by Django 4.1.5 on 2023-01-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_djangosession'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('expire_date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'books_session',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
    ]
